'use client';
import { useState } from 'react';
import {
  ChevronDown,
  ChevronUp,
  FileText,
  Calendar,
  Users,
  Building,
  Truck,
  ArrowLeft,
  BadgeCheck,
} from 'lucide-react';
import { H2 } from '../pagesComponents/pageLayout/Headings';

export default function () {
  const [open, setOpen] = useState(null);

  const toggle = (id) => {
    setOpen(open === id ? null : id);
  };

  const gstReturns = [
    {
      id: 'gstr1',
      title: 'GSTR-1',
      subtitle: 'Outward Supplies Return',
      icon: <FileText className="h-5 w-5" />,
      desc: 'GSTR-1 is a monthly or quarterly return that contains details of all outward supplies of goods and services made by a registered taxpayer. This return forms the basis for availment of input tax credit by the recipients.',
      due: '11th / 13th of next month',
      applies: 'All regular GST taxpayers',
      points: [
        'Filed by all regular GST taxpayers',
        'Monthly filing for turnover > ₹5 crores',
        'Quarterly filing for turnover ≤ ₹5 crores',
        'Due date: 11th of next Contains details of B2B, B2C, exports, and other outward suppliesITC flows to recipients',
      ],
    },
    {
      id: 'gstr2a',
      title: 'GSTR-2A',
      subtitle: 'Auto-populated Purchase Return',
      icon: <ArrowLeft className="h-5 w-5" />,
      desc: 'GSTR-2A is an auto-populated return that shows all inward supplies for which Input Tax Credit (ITC) can be availed. It is generated based on the outward supplies reported by suppliers in their GSTR-1.',
      due: 'Auto-generated (No filing required)',
      applies: 'Available to all GST registered taxpayers',
      points: [
        'Auto-generated by the GST system',
        'No filing required by taxpayer',
        'Updated dynamically as suppliers file GSTR-1',
        'Basis for claiming Input Tax Credit',
        'Contains supplier-wise purchase details',
      ],
    },
    {
      id: 'gstr2b',
      title: 'GSTR-2B',
      subtitle: 'Static Input Tax Credit Statement',
      icon: <Building className="h-5 w-5" />,
      desc: 'GSTR-2B is a static statement that shows eligible Input Tax Credit for a tax period. Unlike GSTR-2A, it remains unchanged after generation and provides a clear picture of ITC available for a specific period.',
      due: '12th of following month (Auto-generated)',
      applies: 'All regular GST taxpayers',
      points: [
        'Generated on 12th of following month',
        'Static document - does not change after generation',
        'Shows eligible ITC for the tax period',
        'Includes details from GSTR-1, GSTR-5, GSTR-6, GSTR-8',
        'More reliable than GSTR-2A for ITC calculation',
      ],
    },
    {
      id: 'gstr3b',
      title: 'GSTR-3B',
      subtitle: 'Monthly Summary Return',
      icon: <Calendar className="h-5 w-5" />,
      desc: 'GSTR-3B is a summary return filed monthly by regular taxpayers. It contains summary of outward supplies, input tax credit claimed, and tax payable. This is a critical return as tax payment is made through this return.',
      due: '20th of following month',
      applies: 'All regular GST taxpayers',
      points: [
        'Monthly filing by all regular taxpayers',
        'Summary of outward and inward supplies',
        'Input Tax Credit claimed and tax liability',
        'Due date: 20th of following month',
        'Tax payment made through this return',
        'Late fee applicable for delayed filing',
      ],
    },
    {
      id: 'gstr4',
      title: 'GSTR-4',
      subtitle: 'Composition Scheme Return',
      icon: <Users className="h-5 w-5" />,
      desc: 'GSTR-4 is a quarterly return filed by taxpayers registered under the Composition Scheme. It contains details of supplies made during the quarter and tax paid under the composition scheme.',
      due: '18th of month following quarter',
      applies: 'Composition scheme taxpayers',
      points: [
        'Filed by composition scheme taxpayers',
        'Quarterly filing requirement',
        'Due date: 18th of month following quarter',
        'Contains summary of supplies and tax paid',
        'Simplified return with minimal compliance',
      ],
    },
    {
      id: 'gstr7',
      title: 'GSTR-7',
      subtitle: 'Tax Deducted at Source Return',
      icon: <Truck className="h-5 w-5" />,
      desc: 'GSTR-7 is filed by persons required to deduct tax at source under GST. This includes government departments, PSUs, and specified entities that deduct tax while making payments to suppliers.',
      due: '10th of following month',
      applies: 'Government departments, PSUs, and specified TDS deductors',
      points: [
        'Filed by TDS deductors under GST',
        'Monthly filing requirement',
        'Due date: 10th of following month',
        'Contains details of TDS deducted and deposited',
        'Applicable to government entities and specified organizations',
      ],
    },
  ];

  return (
    <main className="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950 text-white">
      {/* ================= HEADER ================= */}
      <section className="py-14 text-center">
        <div className="max-w-5xl mx-auto px-4">
          <H2 className="text-3xl md:text-5xl font-semibold">
            Goods and Services Tax (GST) Returns
          </H2>
          <p className="mt-4 text-white/70 max-w-3xl mx-auto text-sm md:text-base">
            Comprehensive guide to GST return filing requirements, due dates,
            and compliance obligations for different categories of taxpayers
            under the GST regime in India.
          </p>
        </div>
      </section>

      {/* ================= CONTENT ================= */}
      <section className="max-w-5xl mx-auto px-4 pb-24 space-y-6">
        {/* INTRO */}
        <GlassCard>
          <h2 className="text-2xl font-bold text-white mb-4">
            Understanding GST Returns
          </h2>
          <p className="text-white/80 leading-relaxed text-sm md:text-base">
            The Goods and Services Tax (GST) system in India requires registered
            taxpayers to file periodic returns containing details of their
            business transactions. These returns serve multiple purposes
            including tax compliance, input tax credit mechanism, and revenue
            collection for the government.
          </p>
          <p>
            Each type of GST return serves a specific purpose and has different
            filing requirements, due dates, and applicability criteria.
            Understanding these requirements is crucial for maintaining GST
            compliance and avoiding penalties.
          </p>
        </GlassCard>

        {/* RETURNS */}
        {gstReturns.map((item, index) => (
          <div
            key={item.id}
            className="rounded-3xl border border-white/10 bg-white/5 backdrop-blur"
          >
            <button
              onClick={() => toggle(item.id)}
              className="w-full flex items-center justify-between px-6 py-5"
            >
              <div className="flex items-center gap-4">
                <div className="h-10 w-10 rounded-xl bg-white/10 border border-white/20 flex items-center justify-center">
                  {item.icon}
                </div>
                <div className="text-left">
                  <h2 className="text-lg font-semibold">
                    {index + 1}. {item.title}
                  </h2>
                  <p className="text-white/60 text-sm">{item.subtitle}</p>
                </div>
              </div>
              {open === item.id ? (
                <ChevronUp className="h-5 w-5 text-white/70" />
              ) : (
                <ChevronDown className="h-5 w-5 text-white/70" />
              )}
            </button>

            {open === item.id && (
              <div className="px-6 pb-6 space-y-4 text-sm md:text-base text-white/80">
                <p>{item.desc}</p>

                <div className="grid sm:grid-cols-2 gap-4">
                  <InfoCard title="Due Date" value={item.due} />
                  <InfoCard title="Applicable To" value={item.applies} />
                </div>

                <ul className="space-y-2">
                  {item.points.map((p, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <BadgeCheck className="h-4 w-4 text-green-400 mt-1" />
                      <span>{p}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ))}

        {/* FOOTER NOTE */}

        <GlassHighlight className="bg-gradient-to-r from-blue-500 to-blue-700 rounded-xl p-8">
          <h4 className="text-white text-xl font-semibold mb-6">
            Important Compliance Notes
          </h4>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 text-white">
            {/* Left Column */}
            <div>
              <h5 className="font-semibold text-lg mb-4">
                Filing Requirements
              </h5>
              <ul className="space-y-2 text-sm text-blue-100 list-disc list-inside">
                <li>
                  Returns must be filed even if there are no transactions (Nil
                  returns)
                </li>
                <li>Late filing attracts penalty and interest charges</li>
                <li>Digital signature or EVC required for filing</li>
              </ul>
            </div>

            {/* Right Column */}
            <div>
              <h5 className="font-semibold text-lg mb-4">Best Practices</h5>
              <ul className="space-y-2 text-sm text-blue-100 list-disc list-inside">
                <li>
                  Maintain proper books of accounts and supporting documents
                </li>
                <li>Reconcile data regularly to avoid discrepancies</li>
                <li>File returns within due dates to avoid penalties</li>
              </ul>
            </div>
          </div>
        </GlassHighlight>
      </section>
    </main>
  );
}

/* ================= REUSABLE UI ================= */

const GlassCard = ({ children }) => (
  <div className="rounded-3xl border border-white/10 bg-white/5 p-6 md:p-8 backdrop-blur">
    {children}
  </div>
);

const GlassHighlight = ({ children }) => (
  <div className="rounded-2xl border border-white/20 bg-white/10 p-5 text-sm text-white/90">
    {children}
  </div>
);

const InfoCard = ({ title, value }) => (
  <div className="rounded-xl border border-white/10 bg-white/5 p-4">
    <p className="text-xs text-white/60">{title}</p>
    <p className="font-semibold">{value}</p>
  </div>
);
