'use client';

import React from 'react';
import Button from '@/components/ui/Button';

export default function PrintPdfButton({
  // what to print (choose one; priority: getContentHtml > results > contentRef/selector)
  results,                 // e.g. [{label:'Principal', value:'₹ 1,00,000'}, ...]
  contentRef,              // React ref to an element on the page
  selector,                // CSS selector (e.g. "#tableId")
  getContentHtml,          // () => string (inner HTML to print)

  // presentation
  title = 'Calculation Results',
  fileName = 'document',   // suggested document name (print dialog)
  logo = '/logo.png',      // optional; set '' to hide
  watermark = 'iTax-Easy', // set '' to disable watermark
  footerText = 'Generated by iTax Easy Calculator',
  extraCss = '',           // optional extra CSS to inject

  // behavior
  closeAfterPrint = true,
  buttonText = 'Download PDF',
  size = 'sm',
  className,
}) {
  // ---------- utils ----------
  const toDataUrl = async (url) => {
    if (!url) return '';
    try {
      const abs = new URL(url, window.location.origin).href;
      const res = await fetch(abs, { cache: 'no-store' });
      const blob = await res.blob();
      const reader = new FileReader();
      return await new Promise((resolve, reject) => {
        reader.onloadend = () => resolve(reader.result);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch {
      return '';
    }
  };

  const escapeHtml = (s = '') =>
    String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');

  const buildWatermarkDataUri = (text = 'iTax-Easy') => {
    if (!text) return '';
    const svg = `
      <svg xmlns='http://www.w3.org/2000/svg' width='280' height='180'>
        <defs>
          <linearGradient id='g' x1='0' x2='1' y1='0' y2='1'>
            <stop offset='0' stop-color='rgb(186,230,253)' stop-opacity='0.20'/>
            <stop offset='1' stop-color='rgb(186,230,253)' stop-opacity='0.20'/>
          </linearGradient>
        </defs>
        <rect width='100%' height='100%' fill='transparent'/>
        <g transform='rotate(-30,140,90)'>
          <text x='20' y='95' font-family='Arial, Helvetica, sans-serif' font-size='34' fill='url(#g)'>
            ${escapeHtml(text)}
          </text>
        </g>
      </svg>`;
    return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
  };

  const fmtDate = (d = new Date()) =>
    new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' });

  // ---------- content builders ----------
  const tableFromResults = () => {
    if (!Array.isArray(results) || !results.length) return '';
    const rows = results
      .map((r) => {
        const label = escapeHtml(r.label ?? '');
        const value = escapeHtml(r.value ?? '');
        const isStrong = /total|final/i.test(label);
        return `<tr><td>${label}</td><td class="val ${isStrong ? 'strong' : ''}">${value}</td></tr>`;
      })
      .join('');
    return `
      <table class="tbl">
        <thead><tr><th>Description</th><th>Value</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>`;
  };

  const cloneFromDom = () => {
    // priority: contentRef > selector
    const node = contentRef?.current || (selector ? document.querySelector(selector) : null);
    if (!node) return '<div class="empty">No data</div>';
    // Shallow sanitize by forbidding scripts in the cloned subtree
    const html = node.cloneNode(true);
    html.querySelectorAll('script').forEach((s) => s.remove());
    return `<div class="html-wrap">${html.outerHTML}</div>`;
  };

  const resolveContentHtml = () => {
    if (typeof getContentHtml === 'function') {
      const html = String(getContentHtml() ?? '');
      return html.trim() ? html : '<div class="empty">No data</div>';
    }
    const table = tableFromResults();
    if (table) return table;
    return cloneFromDom();
  };

  const buildCss = (wmDataUrl) => `
    @page { size: A4; margin: 14mm; }
    * { box-sizing: border-box; }
    html, body { height: 100%; }
    body {
      font: 12.5px/1.35 "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #111827;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .wm {
      position: fixed;
      inset: 0;
      ${wmDataUrl ? `background-image: url('${wmDataUrl}');` : ''}
      background-size: 280px 180px;
      background-repeat: repeat;
      z-index: -1;
    }
    .sheet { width: 100%; }
    .header { text-align: center; margin-bottom: 10px; }
    .logo { height: 28px; display: inline-block; margin-top: 6px; }
    .title { font-size: 16px; font-weight: 700; margin: 10px 0 4px; }
    .date { font-size: 10px; color: #6b7280; margin-bottom: 8px; }
    .rule { height: 1px; background: #e5e7eb; border: 0; margin: 8px 0 12px; }

    .tbl { width: 100%; border-collapse: collapse; }
    .tbl thead th {
      background: #2980b9;
      color: #fff;
      text-align: left;
      font-weight: 700;
      padding: 6px 8px;
      border: 1px solid #d0d7de;
    }
    .tbl td {
      border: 1px solid #e5e7eb;
      padding: 6px 8px;
      vertical-align: top;
    }
    .tbl td.val { text-align: right; }
    .tbl tbody tr:nth-child(odd) td { background: #f9fafb; }
    .strong { font-weight: 700; }

    .html-wrap table { width: 100%; border-collapse: collapse; }
    .html-wrap th, .html-wrap td { border: 1px solid #e5e7eb; padding: 6px 8px; }

    .footer {
      position: fixed;
      bottom: 8mm; left: 0; right: 0;
      text-align: center;
      font-size: 10px; color: #9ca3af;
    }
    .footer .pnums:after { content: counter(page) " / " counter(pages); }
    .brand { color: #64748b; }

    .empty {
      text-align: center;
      color: #9ca3af;
      border: 1px dashed #e5e7eb;
      padding: 16px;
      border-radius: 8px;
    }

    @media print { .noprint { display: none !important; } }

    ${extraCss || ''}
  `;

  const buildHtml = ({ logoDataUrl, wmDataUrl }) => {
    const contentHtml = resolveContentHtml();
    const css = buildCss(wmDataUrl);
    return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>${escapeHtml(fileName)}</title>
    <style>${css}</style>
  </head>
  <body>
    <div class="wm"></div>
    <div class="sheet">
      <div class="header">
        ${logoDataUrl ? `<img class="logo" src="${logoDataUrl}" alt="logo"/>` : ''}
        <div class="title">${escapeHtml(title)}</div>
        <div class="date">Generated on: ${fmtDate()}</div>
        <div class="rule"></div>
      </div>
      ${contentHtml}
    </div>

    <div class="footer">
      <span class="brand">${escapeHtml(footerText)}</span> — <span class="pnums"></span>
    </div>

    <script>
      // Trigger print then (optionally) close
      window.onload = function() { setTimeout(function(){ window.print(); }, 150); };
      window.onafterprint = function() {
        ${closeAfterPrint ? 'try { window.close(); } catch(e) {}' : ''}
      };
    </script>
  </body>
</html>`;
  };

  // ---------- main action ----------
  const exportPdf = async () => {
    const [logoDataUrl, wmDataUrl] = await Promise.all([
      toDataUrl(logo),
      Promise.resolve(buildWatermarkDataUri(watermark)),
    ]);

    const win = window.open('', '_blank', 'noopener,noreferrer,width=900,height=1200');
    if (!win) return;

    const html = buildHtml({ logoDataUrl, wmDataUrl });
    win.document.open();
    win.document.write(html);
    win.document.close();
    try { win.document.title = fileName.replace(/\.pdf$/i, ''); } catch {}
  };

  return (
    <Button onClick={exportPdf} size={size} className={className}>
      {buttonText}
    </Button>
  );
}
