'use client';

import React, { useEffect, useMemo, useState } from 'react';
import { Icon } from '@iconify/react';
import userbackAxios from '@/lib/userbackAxios';
import { DashPage, StatCard, Panel } from '@/components/dashboard/ui';

function formatDate(iso) {
  try {
    return new Date(iso).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return '';
  }
}

const SuperAdminProjectReports = () => {
  const [reports, setReports] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isError, setIsError] = useState(false);
  const [search, setSearch] = useState('');

  const load = async () => {
    try {
      setIsLoading(true);
      setIsError(false);
      const { data } = await userbackAxios.get('/projectreport/all');
      setReports(Array.isArray(data?.data) ? data.data : []);
    } catch (err) {
      console.error('Error fetching project reports:', err);
      setIsError(true);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return reports;
    return reports.filter((r) => {
      const u = r.user || {};
      return (
        r.businessName?.toLowerCase().includes(q) ||
        u.email?.toLowerCase().includes(q) ||
        `${u.firstName || ''} ${u.lastName || ''}`.toLowerCase().includes(q) ||
        u.phone?.toLowerCase().includes(q)
      );
    });
  }, [reports, search]);

  const uniqueUsers = useMemo(
    () => new Set(reports.map((r) => r.userId)).size,
    [reports],
  );

  return (
    <DashPage
      title="Project Reports"
      subtitle="Every project report generated by users"
      icon="mdi:file-document-outline"
      actions={
        <button
          onClick={load}
          disabled={isLoading}
          className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-60"
        >
          <Icon
            icon="lucide:refresh-cw"
            className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`}
          />
          Refresh
        </button>
      }
    >
      <div className="mb-6 grid grid-cols-2 gap-4 sm:grid-cols-3">
        <StatCard
          label="Total Reports"
          value={reports.length}
          icon="mdi:file-document-multiple-outline"
        />
        <StatCard
          label="Users"
          value={uniqueUsers}
          icon="ph:users"
          tone="violet"
        />
        <StatCard
          label="Showing"
          value={filtered.length}
          icon="lucide:filter"
          tone="slate"
        />
      </div>

      <div className="mb-4 relative max-w-md">
        <Icon
          icon="lucide:search"
          className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"
        />
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search by business, user, email, phone"
          className="w-full rounded-lg border border-slate-200 bg-white py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-400"
        />
      </div>

      <Panel bodyClassName="">
        {isLoading ? (
          <div className="flex justify-center py-16">
            <span className="inline-block h-6 w-6 animate-spin rounded-full border-2 border-blue-500 border-b-transparent" />
          </div>
        ) : isError ? (
          <div className="py-14 text-center text-rose-600">
            Failed to load project reports.
          </div>
        ) : filtered.length === 0 ? (
          <div className="py-14 text-center text-slate-500">
            No project reports found.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full text-sm">
              <thead>
                <tr className="border-b border-slate-100 text-left text-slate-500">
                  <th className="px-4 py-3 font-medium">Business</th>
                  <th className="px-4 py-3 font-medium">User</th>
                  <th className="px-4 py-3 font-medium">Contact</th>
                  <th className="px-4 py-3 font-medium">Date</th>
                  <th className="px-4 py-3 font-medium text-right">PDF</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => {
                  const u = r.user || {};
                  return (
                    <tr
                      key={r.id}
                      className="border-b border-slate-50 last:border-0 hover:bg-blue-50/40"
                    >
                      <td className="px-4 py-3 font-semibold text-slate-800">
                        {r.businessName}
                      </td>
                      <td className="px-4 py-3 text-slate-700">
                        {`${u.firstName || ''} ${u.lastName || ''}`.trim() || '—'}
                      </td>
                      <td className="px-4 py-3 text-slate-600">
                        <div>{u.email || '—'}</div>
                        {u.phone && (
                          <div className="text-xs text-slate-400">{u.phone}</div>
                        )}
                      </td>
                      <td className="whitespace-nowrap px-4 py-3 text-slate-500">
                        {formatDate(r.createdAt)}
                      </td>
                      <td className="px-4 py-3 text-right">
                        {r.pdfUrl ? (
                          <a
                            href={r.pdfUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1 rounded-md border border-blue-200 px-3 py-1.5 text-xs font-medium text-blue-600 transition-colors hover:bg-blue-600 hover:text-white"
                          >
                            <Icon icon="lucide:download" className="h-4 w-4" />
                            Download
                          </a>
                        ) : (
                          <span className="text-xs text-slate-400">N/A</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </DashPage>
  );
};

export default SuperAdminProjectReports;
